openapi: 3.2.0
info:
  title: Airflow Dag Version API
  description: Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.
  version: '2'
tags:
- name: DagVersion
paths:
  /api/v2/dags/{dag_id}/dagVersions/{version_number}:
    get:
      tags:
      - DagVersion
      summary: Airflow Get Dag Version
      description: Get one Dag Version.
      operationId: get_dag_version
      security:
      - OAuth2PasswordBearer: []
      - HTTPBearer: []
      parameters:
      - name: dag_id
        in: path
        required: true
        schema:
          type: string
          title: Dag Id
      - name: version_number
        in: path
        required: true
        schema:
          type: integer
          title: Version Number
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DagVersionResponse'
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPExceptionResponse'
          description: Unauthorized
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPExceptionResponse'
          description: Forbidden
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPExceptionResponse'
          description: Not Found
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /api/v2/dags/{dag_id}/dagVersions:
    get:
      tags:
      - DagVersion
      summary: Airflow Get Dag Versions
      description: 'Get all DAG Versions.


        This endpoint allows specifying `~` as the dag_id to retrieve DAG Versions for all DAGs.'
      operationId: get_dag_versions
      security:
      - OAuth2PasswordBearer: []
      - HTTPBearer: []
      parameters:
      - name: dag_id
        in: path
        required: true
        schema:
          type: string
          title: Dag Id
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          minimum: 0
          default: 50
          title: Limit
      - name: offset
        in: query
        required: false
        schema:
          type: integer
          minimum: 0
          default: 0
          title: Offset
      - name: version_number
        in: query
        required: false
        schema:
          type: integer
          title: Version Number
      - name: bundle_name
        in: query
        required: false
        schema:
          type: string
          title: Bundle Name
      - name: bundle_version
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Bundle Version
      - name: order_by
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
          description: 'Attributes to order by, multi criteria sort is supported. Prefix with `-` for descending order. Supported attributes: `id, version_number, bundle_name, bundle_version`'
          default:
          - id
          title: Order By
        description: 'Attributes to order by, multi criteria sort is supported. Prefix with `-` for descending order. Supported attributes: `id, version_number, bundle_name, bundle_version`'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DAGVersionCollectionResponse'
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPExceptionResponse'
          description: Unauthorized
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPExceptionResponse'
          description: Forbidden
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPExceptionResponse'
          description: Not Found
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
        input:
          title: Input
        ctx:
          type: object
          title: Context
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    DAGVersionCollectionResponse:
      properties:
        dag_versions:
          items:
            $ref: '#/components/schemas/DagVersionResponse'
          type: array
          title: Dag Versions
        total_entries:
          type: integer
          title: Total Entries
      type: object
      required:
      - dag_versions
      - total_entries
      title: DAGVersionCollectionResponse
      description: DAG Version Collection serializer for responses.
    HTTPExceptionResponse:
      properties:
        detail:
          anyOf:
          - type: string
          - additionalProperties: true
            type: object
          title: Detail
      type: object
      required:
      - detail
      title: HTTPExceptionResponse
      description: HTTPException Model used for error response.
    DagVersionResponse:
      properties:
        id:
          type: string
          format: uuid
          title: Id
        version_number:
          type: integer
          title: Version Number
        dag_id:
          type: string
          title: Dag Id
        bundle_name:
          anyOf:
          - type: string
          - type: 'null'
          title: Bundle Name
        bundle_version:
          anyOf:
          - type: string
          - type: 'null'
          title: Bundle Version
        created_at:
          type: string
          format: date-time
          title: Created At
        dag_display_name:
          type: string
          title: Dag Display Name
        bundle_url:
          anyOf:
          - type: string
          - type: 'null'
          title: Bundle Url
      type: object
      required:
      - id
      - version_number
      - dag_id
      - bundle_name
      - bundle_version
      - created_at
      - dag_display_name
      - bundle_url
      title: DagVersionResponse
      description: Dag Version serializer for responses.
  securitySchemes:
    OAuth2PasswordBearer:
      type: oauth2
      description: To authenticate Airflow API requests, clients must include a JWT (JSON Web Token) in the Authorization header of each request. This token is used to verify the identity of the client and ensure that they have the appropriate permissions to access the requested resources. You can use the endpoint ``POST /auth/token`` in order to generate a JWT token. Upon successful authentication, the server will issue a JWT token that contains the necessary information (such as user identity and scope) to authenticate subsequent requests. To learn more about Airflow public API authentication, please read https://airflow.apache.org/docs/apache-airflow/stable/security/api.html.
      flows:
        password:
          scopes: {}
          tokenUrl: /auth/token
    HTTPBearer:
      type: http
      scheme: bearer
