openapi: 3.2.0
info:
  contact:
    email: dev@airflow.apache.org
    name: Apache Software Foundation
    url: https://airflow.apache.org
    x-twitter: TheASF
  description: '# Overview


    To facilitate management, Apache Airflow supports a range of REST API endpoints across its

    objects.'
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Airflow API (Stable) Config API
  version: 2.5.3
  x-apisguru-categories:
  - messaging
  x-logo:
    url: https://twitter.com/TheASF/profile_image?size=original
  x-origin:
  - format: openapi
    url: https://airflow.apache.org/docs/apache-airflow/stable/_specs/v1.yaml
    version: '3.0'
  x-providerName: apache.org
  x-serviceName: airflow
servers:
- description: Apache Airflow Stable API.
  url: /api/v1
- url: https://apache.local
security: []
tags:
- name: Config
paths:
  /config:
    get:
      operationId: get_config
      responses:
        '200':
          content:
            application/json:
              example:
                sections:
                - name: core
                  options:
                  - key: dags_folder
                    value: /home/user/my-dags-folder
                - name: smtp
                  options:
                  - key: smtp_host
                    value: localhost
                  - key: smtp_mail_from
                    value: airflow@example.com
              schema:
                $ref: '#/components/schemas/Config'
            text/plain:
              example: '[core]

                dags_folder = /home/user/my-dags-folder

                [smtp]

                smtp_host = localhost

                smtp_mail_from =  airflow@example.com

                '
              schema:
                type: string
          description: Success.
        '401':
          $ref: '#/components/responses/Unauthenticated'
        '403':
          $ref: '#/components/responses/PermissionDenied'
      summary: Apache Airflow Get Current Configuration
      tags:
      - Config
      x-openapi-router-controller: airflow.api_connexion.endpoints.config_endpoint
components:
  schemas:
    Error:
      description: '[RFC7807](https://tools.ietf.org/html/rfc7807) compliant response.

        '
      properties:
        detail:
          description: A human-readable explanation specific to this occurrence of the problem.
          type: string
        instance:
          description: 'A URI reference that identifies the specific occurrence of the problem. It may or may

            not yield further information if dereferenced.

            '
          type: string
        status:
          description: The HTTP status code generated by the API server for this occurrence of the problem.
          type: number
        title:
          description: A short, human-readable summary of the problem type.
          type: string
        type:
          description: 'A URI reference [RFC3986] that identifies the problem type. This specification

            encourages that, when dereferenced, it provide human-readable documentation for

            the problem type.

            '
          type: string
      required:
      - type
      - title
      - status
      type: object
    ConfigSection:
      description: The section of configuration.
      properties:
        name:
          readOnly: true
          type: string
        options:
          items:
            $ref: '#/components/schemas/ConfigOption'
          type: array
      type: object
    Config:
      description: The configuration.
      properties:
        sections:
          items:
            $ref: '#/components/schemas/ConfigSection'
          type: array
      type: object
    ConfigOption:
      description: The option of configuration.
      properties:
        key:
          readOnly: true
          type: string
        value:
          readOnly: true
          type: string
      type: object
  responses:
    Unauthenticated:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Request not authenticated due to missing, invalid, authentication info.
    PermissionDenied:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Client does not have sufficient permission.
  securitySchemes:
    Basic:
      scheme: basic
      type: http
    GoogleOpenId:
      openIdConnectUrl: https://accounts.google.com/.well-known/openid-configuration
      type: openIdConnect
    Kerberos:
      scheme: negotiate
      type: http
externalDocs:
  url: https://airflow.apache.org/docs/apache-airflow/stable/
