openapi: 3.2.0
info:
  contact:
    email: dev@airflow.apache.org
    name: Apache Software Foundation
    url: https://airflow.apache.org
    x-twitter: TheASF
  description: '# Overview


    To facilitate management, Apache Airflow supports a range of REST API endpoints across its

    objects.'
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Airflow API (Stable) Monitoring API
  version: 2.5.3
  x-apisguru-categories:
  - messaging
  x-logo:
    url: https://twitter.com/TheASF/profile_image?size=original
  x-origin:
  - format: openapi
    url: https://airflow.apache.org/docs/apache-airflow/stable/_specs/v1.yaml
    version: '3.0'
  x-providerName: apache.org
  x-serviceName: airflow
servers:
- description: Apache Airflow Stable API.
  url: /api/v1
- url: https://apache.local
security: []
tags:
- name: Monitoring
paths:
  /health:
    get:
      description: 'Get the status of Airflow''s metadatabase and scheduler. It includes info about

        metadatabase and last heartbeat of scheduler.'
      operationId: get_health
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthInfo'
          description: Success.
      summary: Apache Airflow Get Instance Status
      tags:
      - Monitoring
      x-openapi-router-controller: airflow.api_connexion.endpoints.health_endpoint
  /version:
    get:
      operationId: get_version
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionInfo'
          description: Success.
      summary: Apache Airflow Get Version Information
      tags:
      - Monitoring
      x-openapi-router-controller: airflow.api_connexion.endpoints.version_endpoint
components:
  schemas:
    HealthInfo:
      description: Instance status information.
      properties:
        metadatabase:
          $ref: '#/components/schemas/MetadatabaseStatus'
        scheduler:
          $ref: '#/components/schemas/SchedulerStatus'
      type: object
    SchedulerStatus:
      description: The status and the latest scheduler heartbeat.
      properties:
        latest_scheduler_heartbeat:
          description: The time the scheduler last do a heartbeat.
          format: datetime
          readOnly: true
          type:
          - string
          - 'null'
        status:
          $ref: '#/components/schemas/HealthStatus'
      type: object
    VersionInfo:
      description: Version information.
      properties:
        git_version:
          description: The git version (including git commit hash)
          type:
          - string
          - 'null'
        version:
          description: The version of Airflow
          type: string
      type: object
    HealthStatus:
      description: Health status
      enum:
      - healthy
      - unhealthy
      type: string
    MetadatabaseStatus:
      description: The status of the metadatabase.
      properties:
        status:
          $ref: '#/components/schemas/HealthStatus'
      type: object
  securitySchemes:
    Basic:
      scheme: basic
      type: http
    GoogleOpenId:
      openIdConnectUrl: https://accounts.google.com/.well-known/openid-configuration
      type: openIdConnect
    Kerberos:
      scheme: negotiate
      type: http
externalDocs:
  url: https://airflow.apache.org/docs/apache-airflow/stable/
