openapi: 3.2.0
info:
  contact:
    email: dev@airflow.apache.org
    name: Apache Software Foundation
    url: https://airflow.apache.org
    x-twitter: TheASF
  description: '# Overview


    To facilitate management, Apache Airflow supports a range of REST API endpoints across its

    objects.'
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Airflow API (Stable) X Com API
  version: 2.5.3
  x-apisguru-categories:
  - messaging
  x-logo:
    url: https://twitter.com/TheASF/profile_image?size=original
  x-origin:
  - format: openapi
    url: https://airflow.apache.org/docs/apache-airflow/stable/_specs/v1.yaml
    version: '3.0'
  x-providerName: apache.org
  x-serviceName: airflow
servers:
- description: Apache Airflow Stable API.
  url: /api/v1
- url: https://apache.local
security: []
tags:
- name: XCom
paths:
  /dags/{dag_id}/dagRuns/{dag_run_id}/taskInstances/{task_id}/xcomEntries:
    parameters:
    - $ref: '#/components/parameters/DAGID'
    - $ref: '#/components/parameters/DAGRunID'
    - $ref: '#/components/parameters/TaskID'
    get:
      description: This endpoint allows specifying `~` as the dag_id, dag_run_id, task_id to retrieve XCOM entries for for all DAGs, DAG runs and task instances. XCom values won't be returned as they can be large. Use this endpoint to get a list of XCom entries and then fetch individual entry to get value.
      operationId: get_xcom_entries
      parameters:
      - $ref: '#/components/parameters/PageLimit'
      - $ref: '#/components/parameters/PageOffset'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/XComCollection'
          description: Success.
        '401':
          $ref: '#/components/responses/Unauthenticated'
        '403':
          $ref: '#/components/responses/PermissionDenied'
      summary: Apache Airflow List XCom Entries
      tags:
      - XCom
      x-openapi-router-controller: airflow.api_connexion.endpoints.xcom_endpoint
  /dags/{dag_id}/dagRuns/{dag_run_id}/taskInstances/{task_id}/xcomEntries/{xcom_key}:
    parameters:
    - $ref: '#/components/parameters/DAGID'
    - $ref: '#/components/parameters/DAGRunID'
    - $ref: '#/components/parameters/TaskID'
    - $ref: '#/components/parameters/XComKey'
    get:
      operationId: get_xcom_entry
      parameters:
      - description: 'Whether to deserialize an XCom value when using a custom XCom backend.


          The XCom API endpoint calls `orm_deserialize_value` by default since an XCom may contain value

          that is potentially expensive to deserialize in the web server. Setting this to true overrides

          the consideration, and calls `deserialize_value` instead.


          This parameter is not meaningful when using the default XCom backend.


          *New in version 2.4.0*

          '
        in: query
        name: deserialize
        required: false
        schema:
          default: false
          type: boolean
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/XCom'
          description: Success.
        '401':
          $ref: '#/components/responses/Unauthenticated'
        '403':
          $ref: '#/components/responses/PermissionDenied'
        '404':
          $ref: '#/components/responses/NotFound'
      summary: Apache Airflow Get an XCom Entry
      tags:
      - XCom
      x-openapi-router-controller: airflow.api_connexion.endpoints.xcom_endpoint
components:
  schemas:
    CollectionInfo:
      description: Metadata about collection.
      properties:
        total_entries:
          description: 'Count of total objects in the current result set before pagination parameters

            (limit, offset) are applied.

            '
          type: integer
      type: object
    XCom:
      allOf:
      - $ref: '#/components/schemas/XComCollectionItem'
      - properties:
          value:
            description: The value
            type: string
        type: object
      description: Full representations of XCom entry.
    Error:
      description: '[RFC7807](https://tools.ietf.org/html/rfc7807) compliant response.

        '
      properties:
        detail:
          description: A human-readable explanation specific to this occurrence of the problem.
          type: string
        instance:
          description: 'A URI reference that identifies the specific occurrence of the problem. It may or may

            not yield further information if dereferenced.

            '
          type: string
        status:
          description: The HTTP status code generated by the API server for this occurrence of the problem.
          type: number
        title:
          description: A short, human-readable summary of the problem type.
          type: string
        type:
          description: 'A URI reference [RFC3986] that identifies the problem type. This specification

            encourages that, when dereferenced, it provide human-readable documentation for

            the problem type.

            '
          type: string
      required:
      - type
      - title
      - status
      type: object
    XComCollection:
      allOf:
      - properties:
          xcom_entries:
            items:
              $ref: '#/components/schemas/XComCollectionItem'
            type: array
        type: object
      - $ref: '#/components/schemas/CollectionInfo'
      description: 'Collection of XCom entries.


        *Changed in version 2.1.0*&#58; ''total_entries'' field is added.

        '
      type: object
    XComCollectionItem:
      description: 'XCom entry collection item.


        The value field is only available when reading a single object due to the size of the value.

        '
      properties:
        dag_id:
          type: string
        execution_date:
          format: datetime
          type: string
        key:
          type: string
        task_id:
          type: string
        timestamp:
          format: datetime
          type: string
      type: object
  parameters:
    XComKey:
      description: The XCom key.
      in: path
      name: xcom_key
      required: true
      schema:
        type: string
    DAGID:
      description: The DAG ID.
      in: path
      name: dag_id
      required: true
      schema:
        type: string
    PageOffset:
      description: The number of items to skip before starting to collect the result set.
      in: query
      name: offset
      required: false
      schema:
        minimum: 0
        type: integer
    DAGRunID:
      description: The DAG run ID.
      in: path
      name: dag_run_id
      required: true
      schema:
        type: string
    PageLimit:
      description: The numbers of items to return.
      in: query
      name: limit
      required: false
      schema:
        default: 100
        type: integer
    TaskID:
      description: The task ID.
      in: path
      name: task_id
      required: true
      schema:
        type: string
  responses:
    Unauthenticated:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Request not authenticated due to missing, invalid, authentication info.
    PermissionDenied:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Client does not have sufficient permission.
    NotFound:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: A specified resource is not found.
  securitySchemes:
    Basic:
      scheme: basic
      type: http
    GoogleOpenId:
      openIdConnectUrl: https://accounts.google.com/.well-known/openid-configuration
      type: openIdConnect
    Kerberos:
      scheme: negotiate
      type: http
externalDocs:
  url: https://airflow.apache.org/docs/apache-airflow/stable/
