openapi: 3.2.0
info:
  contact:
    email: dev@airflow.apache.org
    name: Apache Software Foundation
    url: https://airflow.apache.org
    x-twitter: TheASF
  description: '# Overview


    To facilitate management, Apache Airflow supports a range of REST API endpoints across its

    objects.'
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Airflow API (Stable) Event Log API
  version: 2.5.3
  x-apisguru-categories:
  - messaging
  x-logo:
    url: https://twitter.com/TheASF/profile_image?size=original
  x-origin:
  - format: openapi
    url: https://airflow.apache.org/docs/apache-airflow/stable/_specs/v1.yaml
    version: '3.0'
  x-providerName: apache.org
  x-serviceName: airflow
servers:
- description: Apache Airflow Stable API.
  url: /api/v1
- url: https://apache.local
security: []
tags:
- name: Event Log
paths:
  /eventLogs:
    get:
      description: List log entries from event log.
      operationId: get_event_logs
      parameters:
      - $ref: '#/components/parameters/PageLimit'
      - $ref: '#/components/parameters/PageOffset'
      - $ref: '#/components/parameters/OrderBy'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventLogCollection'
          description: Success.
        '401':
          $ref: '#/components/responses/Unauthenticated'
        '403':
          $ref: '#/components/responses/PermissionDenied'
      summary: Apache Airflow List Log Entries
      tags:
      - Event Log
      x-openapi-router-controller: airflow.api_connexion.endpoints.event_log_endpoint
  /eventLogs/{event_log_id}:
    parameters:
    - $ref: '#/components/parameters/EventLogID'
    get:
      operationId: get_event_log
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventLog'
          description: Success.
        '401':
          $ref: '#/components/responses/Unauthenticated'
        '403':
          $ref: '#/components/responses/PermissionDenied'
        '404':
          $ref: '#/components/responses/NotFound'
      summary: Apache Airflow Get a Log Entry
      tags:
      - Event Log
      x-openapi-router-controller: airflow.api_connexion.endpoints.event_log_endpoint
components:
  schemas:
    CollectionInfo:
      description: Metadata about collection.
      properties:
        total_entries:
          description: 'Count of total objects in the current result set before pagination parameters

            (limit, offset) are applied.

            '
          type: integer
      type: object
    Error:
      description: '[RFC7807](https://tools.ietf.org/html/rfc7807) compliant response.

        '
      properties:
        detail:
          description: A human-readable explanation specific to this occurrence of the problem.
          type: string
        instance:
          description: 'A URI reference that identifies the specific occurrence of the problem. It may or may

            not yield further information if dereferenced.

            '
          type: string
        status:
          description: The HTTP status code generated by the API server for this occurrence of the problem.
          type: number
        title:
          description: A short, human-readable summary of the problem type.
          type: string
        type:
          description: 'A URI reference [RFC3986] that identifies the problem type. This specification

            encourages that, when dereferenced, it provide human-readable documentation for

            the problem type.

            '
          type: string
      required:
      - type
      - title
      - status
      type: object
    EventLog:
      description: Log of user operations via CLI or Web UI.
      properties:
        dag_id:
          description: The DAG ID
          readOnly: true
          type:
          - string
          - 'null'
        event:
          description: A key describing the type of event.
          readOnly: true
          type: string
        event_log_id:
          description: The event log ID
          readOnly: true
          type: integer
        execution_date:
          description: 'When the event was dispatched for an object having execution_date, the value of this field.

            '
          format: date-time
          readOnly: true
          type:
          - string
          - 'null'
        extra:
          description: 'Other information that was not included in the other fields, e.g. the complete CLI command.

            '
          readOnly: true
          type:
          - string
          - 'null'
        owner:
          description: Name of the user who triggered these events a.
          readOnly: true
          type: string
        task_id:
          description: The DAG ID
          readOnly: true
          type:
          - string
          - 'null'
        when:
          description: The time when these events happened.
          format: date-time
          readOnly: true
          type: string
      type: object
    EventLogCollection:
      allOf:
      - properties:
          event_logs:
            items:
              $ref: '#/components/schemas/EventLog'
            type: array
        type: object
      - $ref: '#/components/schemas/CollectionInfo'
      description: 'Collection of event logs.


        *Changed in version 2.1.0*&#58; ''total_entries'' field is added.

        '
      type: object
  parameters:
    EventLogID:
      description: The event log ID.
      in: path
      name: event_log_id
      required: true
      schema:
        type: integer
    OrderBy:
      description: 'The name of the field to order the results by.

        Prefix a field name with `-` to reverse the sort order.


        *New in version 2.1.0*

        '
      in: query
      name: order_by
      required: false
      schema:
        type: string
    PageOffset:
      description: The number of items to skip before starting to collect the result set.
      in: query
      name: offset
      required: false
      schema:
        minimum: 0
        type: integer
    PageLimit:
      description: The numbers of items to return.
      in: query
      name: limit
      required: false
      schema:
        default: 100
        type: integer
  responses:
    Unauthenticated:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Request not authenticated due to missing, invalid, authentication info.
    PermissionDenied:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Client does not have sufficient permission.
    NotFound:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: A specified resource is not found.
  securitySchemes:
    Basic:
      scheme: basic
      type: http
    GoogleOpenId:
      openIdConnectUrl: https://accounts.google.com/.well-known/openid-configuration
      type: openIdConnect
    Kerberos:
      scheme: negotiate
      type: http
externalDocs:
  url: https://airflow.apache.org/docs/apache-airflow/stable/
