# x-archived-from: airflow-dagwarning-api-openapi.yml
# x-archived-on: 2026-09-26
openapi: 3.2.0
info:
  title: Airflow Dag Warning API
  description: Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.
  version: '2'
tags:
- name: DagWarning
paths:
  /api/v2/dagWarnings:
    get:
      tags:
      - DagWarning
      summary: Airflow List Dag Warnings
      description: Get a list of DAG warnings.
      operationId: list_dag_warnings
      security:
      - OAuth2PasswordBearer: []
      - HTTPBearer: []
      parameters:
      - name: dag_id
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Dag Id
      - name: warning_type
        in: query
        required: false
        schema:
          anyOf:
          - $ref: '#/components/schemas/DagWarningType'
          - type: 'null'
          title: Warning Type
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          minimum: 0
          default: 50
          title: Limit
      - name: offset
        in: query
        required: false
        schema:
          type: integer
          minimum: 0
          default: 0
          title: Offset
      - name: order_by
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
          description: 'Attributes to order by, multi criteria sort is supported. Prefix with `-` for descending order. Supported attributes: `dag_id, warning_type, message, timestamp`'
          default:
          - dag_id
          title: Order By
        description: 'Attributes to order by, multi criteria sort is supported. Prefix with `-` for descending order. Supported attributes: `dag_id, warning_type, message, timestamp`'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DAGWarningCollectionResponse'
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPExceptionResponse'
          description: Unauthorized
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPExceptionResponse'
          description: Forbidden
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    HTTPExceptionResponse:
      properties:
        detail:
          anyOf:
          - type: string
          - additionalProperties: true
            type: object
          title: Detail
      type: object
      required:
      - detail
      title: HTTPExceptionResponse
      description: HTTPException Model used for error response.
    DAGWarningCollectionResponse:
      properties:
        dag_warnings:
          items:
            $ref: '#/components/schemas/DAGWarningResponse'
          type: array
          title: Dag Warnings
        total_entries:
          type: integer
          title: Total Entries
      type: object
      required:
      - dag_warnings
      - total_entries
      title: DAGWarningCollectionResponse
      description: DAG warning collection serializer for responses.
    DagWarningType:
      type: string
      enum:
      - asset conflict
      - non-existent pool
      - runtime varying value
      title: DagWarningType
      description: 'Enum for DAG warning types.


        This is the set of allowable values for the ``warning_type`` field

        in the DagWarning model.'
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
        input:
          title: Input
        ctx:
          type: object
          title: Context
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    DAGWarningResponse:
      properties:
        dag_id:
          type: string
          title: Dag Id
        warning_type:
          $ref: '#/components/schemas/DagWarningType'
        message:
          type: string
          title: Message
        timestamp:
          type: string
          format: date-time
          title: Timestamp
        dag_display_name:
          type: string
          title: Dag Display Name
      type: object
      required:
      - dag_id
      - warning_type
      - message
      - timestamp
      - dag_display_name
      title: DAGWarningResponse
      description: DAG Warning serializer for responses.
  securitySchemes:
    OAuth2PasswordBearer:
      type: oauth2
      description: To authenticate Airflow API requests, clients must include a JWT (JSON Web Token) in the Authorization header of each request. This token is used to verify the identity of the client and ensure that they have the appropriate permissions to access the requested resources. You can use the endpoint ``POST /auth/token`` in order to generate a JWT token. Upon successful authentication, the server will issue a JWT token that contains the necessary information (such as user identity and scope) to authenticate subsequent requests. To learn more about Airflow public API authentication, please read https://airflow.apache.org/docs/apache-airflow/stable/security/api.html.
      flows:
        password:
          scopes: {}
          tokenUrl: /auth/token
    HTTPBearer:
      type: http
      scheme: bearer
